blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://learn.microsoft.com/en-us/minecraft/creator/documents/chunkeroverview?view=minecraft-bedrock-stable
    about: A guide on how to use Chunker.